### ISSUE TITLE
gs.execute with stdin does not work properly

### ISSUE THREAD

**Issue by maxfragg** [mjdorma/pyvbox#8]
> /usr/local/lib/python2.7/dist-packages/pyvbox-0.1->py2.7.egg/virtualbox/library_ext/guest_session.pyc in execute(self, command, >arguments, stdin, environment, flags, priority, affinity, timeout_ms)
>     59             while index < len(stdin):
>     60                 index += process.write(0, [library.ProcessInputFlag.none], 
> ---> 61                                         stdin[index:], 0)
>     62             process.write(0, [library.ProcessInputFlag.end_of_file], 0)
>     63 
> 
> /usr/local/lib/python2.7/dist-packages/pyvbox-0.1-py2.7.egg/virtualbox/library.pyc in >write(self, handle, flags, data, timeout_ms)
>  13748             raise TypeError("handle can only be an instance of type baseinteger")
>  13749         if not isinstance(flags, baseinteger):
>  13750             raise TypeError("flags can only be an instance of type baseinteger")
>  13751         if not isinstance(data, list):
>  13752             raise TypeError("data can only be an instance of type list")
> 
> TypeError: flags can only be an instance of type baseinteger

i get this error, when ever trying to use execute with input.

calling process.write() manualy with 0 instead of [library.ProcessInputFlag.none] seams to work, but then i get a type error for the stdin, no matter what i put there, it really should be a string, right? 
I'm not really sure, but it looks like the error checks in the process.write() don't work properly.
And the following process.write(0, [library.ProcessInputFlag.end_of_file], 0) will probably fail as well, since write takes exactly 5 arguments and omitting stdin will probably crash as well.

**Comment by SethMichaelLarson** [comment]
I believe the API is working again so this issue can be closed.

**Comment by Smarre** [comment]
I do see this issue still, though...

    password = "foo"
    self.guest_session.execute("/usr/bin/passwd", arguments=["build"], stdin=password)

This fails with `TypeError: data can only be an instance of type list`, caused by `execute()` to pass a map instead of list to `write_array()` as `data` argument.

**Comment by mjdorma** [comment]
> I do see this issue still, though...
> 
> ```
> password = "foo"
> self.guest_session.execute("/usr/bin/passwd", arguments=["build"], stdin=password)
> ```
> 
> This fails with `TypeError: data can only be an instance of type list`, caused by `execute()` to pass a map instead of list to `write_array()` as `data` argument.

Try adding the password to a list. [password] ?

Assume your issue is @ https://github.com/sethmlarson/virtualbox-python/blob/d48da8a828fab8bafa425d8d859249ad7d752a50/virtualbox/library_ext/guest_session.py#L80

Process write_array : https://pythonhosted.org/pyvbox/virtualbox/library.html#virtualbox.library.IGuestProcess.write_array

... finally check the code gen for this interface 


```
if not isinstance(data, list):
    raise TypeError("data can only be an instance of type list")

for a in data[:10]:
    if not isinstance(a, basestring):
        raise TypeError("array can only contain objects of ....
```

**Comment by Smarre** [comment]
> 
> Try adding the password to a list. [password] ?

Still gives the same error.

> 
> Failing that, you could test adding an override to the code generate interface for write_array under the guest process extension module? Force it to accept the string.

Well, forcing it to accept a string won’t help, since it won’t get a string, but a map. The `execute()` convenience method converts the input string to a map of unicode characters, where `write()` (and I suppose `write_array()`, though I’m not sure what’s the actual difference between the two) expects a list of unicode characters (which is what Virtualbox wants).

My guess is that changing the map to utilize a list would make this work better. I converted to use `process_start()` and am passing arguments in with slighty modified converter:

    bytearray = [str(ord(char)) for char in password]

Though honestly, I’d rather be able to pass a stream instead, so I could just write whatever I’d need to. But that probably would need some threading logic.

**Comment by mjdorma** [comment]
Ha, that’s what I get for using a phone to read old code. Ok, that makes sense. 

So the simple win is to wrap the map up with list() in the execute helper? 

`array = list(map(lambda a: str(ord(a)), stdin[index:]))`

**Comment by Smarre** [comment]
Python is not my forte (using it for a work project out of necessity), so I can’t comment on what would be a good way to solve it. I used my version because it was simplest one I was able to figure out.
